spring.application.name=camel-file
camel.main.run-controller=true

camel.properties.noop=true
exchangeProperty.destName=payment


#jms connection properties
spring.artemis.broker-url=tcp://localhost:61616
spring.artemis.user=artemis
spring.artemis.password=artemis